// This function should retrieve the JSON from the `countryURL` and then call onCountryDataReceived() with the JSON
function getShowsData(URL, callback) {
  fetch(URL)
    // Get the response and extract the JSON
    .then(function (response) {
      return response.json();
    })
    // Do something with the JSON
    .then((data) => {
      callback(data);
      // console.log(data);
    })
    // If something goes wrong
    .catch((error) => console.log(error));
}

//DO NOT EDIT THIS FILE

//This content is from https://www.tvmaze.com/
//specifically: https://api.tvmaze.com/shows

function getOneShow() {
  return {
    id: 82,
    url: "https://api.tvmaze.com/shows/82/episodes",
    name: "Game of Thrones",
    type: "Scripted",
    language: "English",
    genres: ["Drama", "Adventure", "Fantasy"],
    status: "Ended",
    runtime: 60,
    premiered: "2011-04-17",
    officialSite: "http://www.hbo.com/game-of-thrones",
    schedule: { time: "21:00", days: ["Sunday"] },
    rating: { average: 9.1 },
    weight: 97,
    network: {
      id: 8,
      name: "HBO",
      country: {
        name: "United States",
        code: "US",
        timezone: "America/New_York",
      },
    },
    webChannel: {
      id: 22,
      name: "HBO Go",
      country: {
        name: "United States",
        code: "US",
        timezone: "America/New_York",
      },
    },
    externals: { tvrage: 24493, thetvdb: 121361, imdb: "tt0944947" },
    image: {
      medium:
        "http://static.tvmaze.com/uploads/images/medium_portrait/190/476117.jpg",
      original:
        "http://static.tvmaze.com/uploads/images/original_untouched/190/476117.jpg",
    },
    summary:
      "<p>Based on the bestselling book series <i>A Song of Ice and Fire</i> by George R.R. Martin, this sprawling new HBO drama is set in a world where summers span decades and winters can last a lifetime. From the scheming south and the savage eastern lands, to the frozen north and ancient Wall that protects the realm from the mysterious darkness beyond, the powerful families of the Seven Kingdoms are locked in a battle for the Iron Throne. This is a story of duplicity and treachery, nobility and honor, conquest and triumph. In the <b>Game of Thrones</b>, you either win or you die.</p>",
    updated: 1580402781,
    _links: {
      self: { href: "hhttp://www.hbo.com/game-of-thrones2" },
      previousepisode: { href: "http://www.hbo.com/game-of-thrones" },
    },
  };
}

